name: Lint Checker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - uses: pnpm/action-setup@v2
      with:
        version: 8

    - name: Use Node.js 18.17.1
      uses: actions/setup-node@v2
      with:
        node-version: 18.17.1
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install

    - name: Run Eslint
      run: pnpm lint:fix

    - name: Run Prettier
      run: pnpm prettify

    - name: Check for Linting Changes
      run: |
        git diff --exit-code || (echo "Linting changes were found. Run 'pnpm lint:fix && pnpm prettify' locally and commit the changes." && exit 1)
